### PR TITLE
Remove deprecated pytest_namespace

### LINKED ISSUE #8: PluginValidationError when plugin is installed
Having installed the nose2pytest 'plugin' I cannot run pytest anymore
```
pluggy.manager.PluginValidationError: unknown hook 'pytest_namespace'
```
I tried 
```
-p no:nose2pytest
```
but no success

The recommended replacement would be ```pytest_configure``` https://docs.pytest.org/en/latest/deprecations.html#pytest-namespace

The hook was removed: https://github.com/pytest-dev/pytest/pull/4421/files

### PR DESCRIPTION
**Pull request by PhilippSelenium**
Fix https://github.com/pytest-dev/nose2pytest/issues/8

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]

**Comment by PhilippSelenium** [comment]
@nicoddemus I'm new to this. Does this need another approval or do I have to close the MR?

**Comment by nicoddemus** [comment]
@schollii is the main maintainer, we should ask for his input first. 😁

**Comment by schollii** [comment]
Thanks let me have  a look

**Review by schollii — CHANGES_REQUESTED** [review]
The tests pass and @PhilippSelenium your own use of plugin with pytest works with your fix so in theory, it *should* be good to merge. 

However one concern is that the tests did not fail prior... @PhilippSelenium do you mind checking if the problem was caught prior, maybe this got missed because they are not run regularly, not sure. If no test failure with old code, could you add a test that exercises the hook, so if it changes again the future, we'll know.

**Comment by PhilippSelenium** [comment]
@schollii The tests do fail on master branch with the latest pytest version:
```
pluggy.manager.PluginValidationError: unknown hook 'pytest_namespace' in plugin
```
The problem is that the tests have not been run since 2016. Is there a possibility to enable nightly or at least weekly builds?
Or do you as a maintainer have the possibility to trigger a testrun on master?

**Comment by PhilippSelenium** [comment]
ping

**Comment by schollii** [comment]
@Nicodemus I've been out of the loop on such details what do you recommend to resolve this, does setting this up require anything from me?

**Comment by nicoddemus** [comment]
Hi @schollii,

Can you access https://travis-ci.org/github/pytest-dev/nose2pytest/settings?

**Comment by nicoddemus** [comment]
(Regardless, I think this is good to merge and release 👍)

**Pull request merged**
