### PR TITLE
Replace Travis CI with GitHub Actions

### PR DESCRIPTION
**Pull request by hugovk**
Travis CI is being turned off for the pytest-dev org ([internal discussion](https://github.com/orgs/pytest-dev/teams/contributors/discussions/5)), due to the recent security handling ([1](https://twitter.com/peter_szilagyi/status/1437646118700175360), [2](https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/)).

This PR replaces Travis CI with GitHub Actions. It mostly replicates the old Travis workflow, the main differences is it runs using tox and adds caching.

And just like the last [Travis build](https://travis-ci.org/github/pytest-dev/nose2pytest/builds/759678543), it also fails for Python 3.8. I didn't look into it but it's a [known issue](https://github.com/pytest-dev/nose2pytest/issues/15#issuecomment-726788746) so we have parity.

I also noticed that Python 3.7.1 (the last Travis CI build) and 3.7.7 (what I have on my machine) passed, but the latest `3.7` version on GHA (3.7.12) failed. So I've pinned to 3.7.7 in the CI. https://github.com/pytest-dev/nose2pytest/issues/15#issuecomment-726788746 also noted 3.7 failed, so this will need checking in the future (as part of #15).

Also, drop support for Python 3.4, it's not available on GHA, and anyway is EOL. We should also drop EOL 3.5 too. Shall I also remove it here?

Also, update Trove classifiers.

Finally, drop the dot in py.test :) https://twitter.com/pytestdotorg/status/753767547866972160

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]

**Comment by hugovk** [comment]
Here's an example build:

https://github.com/hugovk/nose2pytest/actions/runs/1254263380

Please could someone enable GHA for this repo at https://github.com/pytest-dev/nose2pytest/actions?

**Comment by nicoddemus** [comment]
> Please could someone enable GHA for this repo at pytest-dev/nose2pytest/actions?

Hmm how? Just create a dummy Python workflow?

Because I'm happy to just merge this and fix anything not working as it should afterward.

**Comment by hugovk** [comment]
If there's no big "Enable Actions button" at https://github.com/pytest-dev/nose2pytest/actions, then let's just merge and fix from there! Thanks!

**Comment by nicoddemus** [comment]
Yeah I don't see anything like that. 😁 

Merging, thanks a lot for tackling this. 👍

**Comment by nicoddemus** [comment]
Running: https://github.com/pytest-dev/nose2pytest/actions/runs/1254290050 👍

**Pull request merged**
